// Auto-generated. Do not edit!

// (in-package sorohack_tree.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class BTFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.bt_status = null;
    }
    else {
      if (initObj.hasOwnProperty('bt_status')) {
        this.bt_status = initObj.bt_status
      }
      else {
        this.bt_status = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type BTFeedback
    // Serialize message field [bt_status]
    bufferOffset = _serializer.string(obj.bt_status, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type BTFeedback
    let len;
    let data = new BTFeedback(null);
    // Deserialize message field [bt_status]
    data.bt_status = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.bt_status.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'sorohack_tree/BTFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b2038d49540c2888b40df82bb8f9325e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback is the same as the result for a BT action
    string bt_status
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new BTFeedback(null);
    if (msg.bt_status !== undefined) {
      resolved.bt_status = msg.bt_status;
    }
    else {
      resolved.bt_status = ''
    }

    return resolved;
    }
};

module.exports = BTFeedback;
