// Auto-generated. Do not edit!

// (in-package sorohack_tree.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class BTGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.bt_action_goal = null;
    }
    else {
      if (initObj.hasOwnProperty('bt_action_goal')) {
        this.bt_action_goal = initObj.bt_action_goal
      }
      else {
        this.bt_action_goal = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type BTGoal
    // Serialize message field [bt_action_goal]
    bufferOffset = _serializer.string(obj.bt_action_goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type BTGoal
    let len;
    let data = new BTGoal(null);
    // Deserialize message field [bt_action_goal]
    data.bt_action_goal = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.bt_action_goal.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'sorohack_tree/BTGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '089d672a9a4e6b26982ebad40e0104ea';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal of the action, since this is a general action, a string is ok
    string bt_action_goal
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new BTGoal(null);
    if (msg.bt_action_goal !== undefined) {
      resolved.bt_action_goal = msg.bt_action_goal;
    }
    else {
      resolved.bt_action_goal = ''
    }

    return resolved;
    }
};

module.exports = BTGoal;
