; Auto-generated. Do not edit!


(cl:in-package sorohack_tree-msg)


;//! \htmlinclude BTResult.msg.html

(cl:defclass <BTResult> (roslisp-msg-protocol:ros-message)
  ((bt_status
    :reader bt_status
    :initarg :bt_status
    :type cl:string
    :initform ""))
)

(cl:defclass BTResult (<BTResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BTResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BTResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sorohack_tree-msg:<BTResult> is deprecated: use sorohack_tree-msg:BTResult instead.")))

(cl:ensure-generic-function 'bt_status-val :lambda-list '(m))
(cl:defmethod bt_status-val ((m <BTResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sorohack_tree-msg:bt_status-val is deprecated.  Use sorohack_tree-msg:bt_status instead.")
  (bt_status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BTResult>) ostream)
  "Serializes a message object of type '<BTResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'bt_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'bt_status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BTResult>) istream)
  "Deserializes a message object of type '<BTResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'bt_status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'bt_status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BTResult>)))
  "Returns string type for a message object of type '<BTResult>"
  "sorohack_tree/BTResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BTResult)))
  "Returns string type for a message object of type 'BTResult"
  "sorohack_tree/BTResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BTResult>)))
  "Returns md5sum for a message object of type '<BTResult>"
  "b2038d49540c2888b40df82bb8f9325e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BTResult)))
  "Returns md5sum for a message object of type 'BTResult"
  "b2038d49540c2888b40df82bb8f9325e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BTResult>)))
  "Returns full string definition for message of type '<BTResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result of the action, SUCCESS, FAILURE, RUNNING~%string bt_status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BTResult)))
  "Returns full string definition for message of type 'BTResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result of the action, SUCCESS, FAILURE, RUNNING~%string bt_status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BTResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'bt_status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BTResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BTResult
    (cl:cons ':bt_status (bt_status msg))
))
