// Generated by gencpp from file sorohack_tree/BTFeedback.msg
// DO NOT EDIT!


#ifndef SOROHACK_TREE_MESSAGE_BTFEEDBACK_H
#define SOROHACK_TREE_MESSAGE_BTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sorohack_tree
{
template <class ContainerAllocator>
struct BTFeedback_
{
  typedef BTFeedback_<ContainerAllocator> Type;

  BTFeedback_()
    : bt_status()  {
    }
  BTFeedback_(const ContainerAllocator& _alloc)
    : bt_status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _bt_status_type;
  _bt_status_type bt_status;





  typedef boost::shared_ptr< ::sorohack_tree::BTFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sorohack_tree::BTFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct BTFeedback_

typedef ::sorohack_tree::BTFeedback_<std::allocator<void> > BTFeedback;

typedef boost::shared_ptr< ::sorohack_tree::BTFeedback > BTFeedbackPtr;
typedef boost::shared_ptr< ::sorohack_tree::BTFeedback const> BTFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sorohack_tree::BTFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sorohack_tree::BTFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sorohack_tree

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sorohack_tree': ['/home/igmitsio/pepper_ws/devel/share/sorohack_tree/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sorohack_tree::BTFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sorohack_tree::BTFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sorohack_tree::BTFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sorohack_tree::BTFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sorohack_tree::BTFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sorohack_tree::BTFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sorohack_tree::BTFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2038d49540c2888b40df82bb8f9325e";
  }

  static const char* value(const ::sorohack_tree::BTFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2038d49540c2888ULL;
  static const uint64_t static_value2 = 0xb40df82bb8f9325eULL;
};

template<class ContainerAllocator>
struct DataType< ::sorohack_tree::BTFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sorohack_tree/BTFeedback";
  }

  static const char* value(const ::sorohack_tree::BTFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sorohack_tree::BTFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback is the same as the result for a BT action\n\
string bt_status\n\
\n\
";
  }

  static const char* value(const ::sorohack_tree::BTFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sorohack_tree::BTFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bt_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BTFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sorohack_tree::BTFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sorohack_tree::BTFeedback_<ContainerAllocator>& v)
  {
    s << indent << "bt_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.bt_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOROHACK_TREE_MESSAGE_BTFEEDBACK_H
